#---------------------------------#
#      general configuration      #
#---------------------------------#

version: '{build}'

skip_commits:
  files:
    - '**/*.md'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

for:
-
  matrix:
    only:
      - platform: Win32
  
  environment:
    CMAKE_GENERATOR: Visual Studio 15 2017
    CMAKE_INSTALL: install_x86
    INSTALLER_PROJECT: tools\install\mDNSInstall_x86.wixproj

-
  matrix:
    only:
      - platform: x64
    
  environment:
    CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    CMAKE_INSTALL: install_x64
    INSTALLER_PROJECT: tools\install\mDNSInstall_x64.wixproj

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - Win32
  - x64

configuration: Release

before_build:
  - cmd: |-
      mkdir build
      cd build
      cmake --version
      cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=%CMAKE_INSTALL% ..

build:
  parallel: true                 # enable MSBuild parallel builds
  project: build\mDNSWindows.sln # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal

after_build:
  - cmd: |-
      cmake -P cmake_install.cmake
      7z a mDNSWindows_%PLATFORM%.zip .\%CMAKE_INSTALL%\*
      msbuild .\%INSTALLER_PROJECT%

artifacts:
  - path: build/mDNSWindows_Win32.zip
    name: mDNSWindows 32-bit artifacts
  - path: build/mDNSWindows_x64.zip
    name: mDNSWindows 64-bit artifacts
  - path: tools/install/bin/Release/ETC_mDNSInstall_x86.msm
    name: mDNSWindows 32-bit merge module
  - path: tools/install/bin/Release/ETC_mDNSInstall_x64.msm
    name: mDNSWindows 64-bit merge module
