#---------------------------------#
#      general configuration      #
#---------------------------------#

version: '{build}'

skip_commits:
  files:
    - '**/*.md'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

platform:
  - Win32
  - x64

configuration: Release

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

for:
-
  matrix:
    only:
      - platform: Win32
  
  environment:
    CMAKE_GENERATOR: Visual Studio 15 2017
    CMAKE_INSTALL: install_x86
    INSTALLER_PROJECT: tools\install\mDNSInstall_x86.wixproj
    INSTALLER_PROJECT_PLATFORM: x86
    INSTALLER_ARTIFACT: tools\install\bin\Release\ETC_mDNSInstall_x86.msm

  artifacts:
    - path: build/mDNSWindows_Win32.zip
      name: mDNSWindows 32-bit artifacts

-
  matrix:
    only:
      - platform: x64
    
  environment:
    CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    CMAKE_INSTALL: install_x64
    INSTALLER_PROJECT: tools\install\mDNSInstall_x64.wixproj
    INSTALLER_PROJECT_PLATFORM: x64
    INSTALLER_ARTIFACT: tools\install\bin\Release\ETC_mDNSInstall_x64.msm

  artifacts:
    - path: build/mDNSWindows_x64.zip
      name: mDNSWindows 64-bit artifacts

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - cmd: |-
      mkdir build
      cd build
      cmake --version
      cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=%CMAKE_INSTALL% ..

build:
  parallel: true                 # enable MSBuild parallel builds
  project: build\mDNSWindows.sln # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal

after_build:
  - cmd: |-
      cmake -P cmake_install.cmake
      msbuild /m /p:Platform=%INSTALLER_PROJECT_PLATFORM% ..\%INSTALLER_PROJECT%
      mkdir .\%CMAKE_INSTALL%\merge_module
      cp ..\%INSTALLER_ARTIFACT% .\%CMAKE_INSTALL%\merge_module
      7z a mDNSWindows_%PLATFORM%.zip .\%CMAKE_INSTALL%\*
