#---------------------------------#
#      general configuration      #
#---------------------------------#

version: '{build}'

branches:
  only:
    - develop
    - master

skip_commits:
  files:
    - '**/*.md'

#---------------------------------#
#    environment configuration    #
#---------------------------------#

image: Visual Studio 2017

platform:
  - Win32
  - x64

configuration: Release

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

for:
-
  matrix:
    only:
      - platform: Win32
  
  environment:
    CMAKE_GENERATOR: Visual Studio 15 2017

  after_build:
    - cmd: |-
        cmake -P cmake_install.cmake
        msbuild /m /p:Platform=x86 ..\tools\install\mDNSInstall.wixproj
        copy ..\tools\install\bin\Release\ETC_mDNSInstall.msm .
        rmdir /s /q .\install\bin
        7z a mDNSWindows_x86.zip .\install\*

  artifacts:
    - path: build/mDNSWindows_x86.zip
      name: mDNSWindows 32-bit artifacts
    - path: build/ETC_mDNSInstall.msm
      name: mDNSWindows DNS-SD Service Merge Module

-
  matrix:
    only:
      - platform: x64
    
  environment:
    CMAKE_GENERATOR: Visual Studio 15 2017 Win64

  after_build:
    - cmd: |-
        cmake -P cmake_install.cmake
        rmdir /s /q .\install\bin
        7z a mDNSWindows_x64.zip .\install\*

  artifacts:
    - path: build/mDNSWindows_x64.zip
      name: mDNSWindows 64-bit artifacts

#---------------------------------#
#       build configuration       #
#---------------------------------#

before_build:
  - cmd: |-
      mkdir build
      cd build
      cmake --version
      cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=install ..

build:
  parallel: true                 # enable MSBuild parallel builds
  project: build\mDNSWindows.sln # path to Visual Studio solution or project

  # MSBuild verbosity level
  verbosity: minimal
