# This is the Azure CI Pipeline for the mDNSWindows repository.
# The job builds the DLL library for 32- and 64-bit Windows and the service
# installer merge module for 32-bit Windows. This binary package is deployed on
# tagged builds to Bintray.

trigger:
  branches:
    include:
    - develop
    - master
    - release/*
    - refs/tags/v*.*.*.*

pr:
- develop

stages:
- stage: build
  displayName: 'Build mDNSWindows'
  jobs:
  # Build mDNSWindows on Windows using CMake and Visual Studio 2017.
  - job: windows_build
    displayName: 'VS2017'
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        Win32:
          cmake_generator: 'Visual Studio 15 2017'
          artifact_type: x86
        x64:
          cmake_generator: 'Visual Studio 15 2017 Win64'
          artifact_type: x64
    steps:
      - script: |
          cd $(Build.SourcesDirectory)
          mkdir build
          cd build
          cmake --version
          cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX=install ..
        displayName: 'Configure Project'
      - task: VSBuild@1
        displayName: 'Build Project'
        inputs:
          solution: $(Build.SourcesDirectory)\build\mDNSWindows.sln
          configuration: Release
      - script: |
          cd $(Build.SourcesDirectory)\build
          cmake -P cmake_install.cmake
        displayName: 'Install Project Artifacts'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.SourcesDirectory)\build\install'
          artifactName: 'mdnswindows_$(artifact_type)'
  - job: windows_merge_module
    dependsOn: windows_build
    displayName: 'Installer merge module'
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: 'Download x86 Build Artifacts'
        inputs:
          artifactName: mdnswindows_x86
          downloadPath: $(Build.SourcesDirectory)\build
      - script: |
          cd $(Build.SourcesDirectory)\build
          ren mdnswindows_x86 install
        displayName: 'Rename artifact folder'
      - task: VSBuild@1
        inputs:
          solution: $(Build.SourcesDirectory)\tools\install\mDNSInstall.sln
          platform: x86
          configuration: Release
        displayName: 'Build Windows Installer'
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: '$(Build.SourcesDirectory)\tools\install\bin\Release\ETC_mDNSInstall.msm'
          artifactName: 'mdnswindows_merge_x86'

- stage: deploy_binaries
  displayName: 'Deploy mDNSWindows Binaries'
  condition: and(succeeded('build'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  jobs:
  - job: bintray_deploy
    displayName: 'BinTray Deploy'
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
    - script: |
        cd tools/version
        version=$(<current_version.txt)
        echo "##vso[task.setvariable variable=mDNSWindowsVersion]$version"
      displayName: 'Obtain mDNSWindows Version'
    - template: tools/ci/azure_templates/deploy_artifact_zip.yml
      parameters:
        artifactName: mdnswindows_x86
        artifactTargetFile: mDNSWindows_$(mDNSWindowsVersion)_x86.zip
        artifactVersion: $(mDNSWindowsVersion)
    - template: tools/ci/azure_templates/deploy_artifact_zip.yml
      parameters:
        artifactName: mdnswindows_x64
        artifactTargetFile: mDNSWindows_$(mDNSWindowsVersion)_x64.zip
        artifactVersion: $(mDNSWindowsVersion)
    - template: tools/ci/azure_templates/deploy_artifact.yml
      parameters:
        artifactName: mdnswindows_merge_x86
        artifactSourceFile: ETC_mDNSInstall.msm
        artifactTargetFile: mDNSWindows_Merge_$(mDNSWindowsVersion).msm
        artifactVersion: $(mDNSWindowsVersion)
